### ISSUE TITLE
Constellations styles does not apply

### ISSUE THREAD

**Issue by maisteRR** [ofrohn/d3-celestial#92]
Hi, community
Why this code doesn't work? 

>               Celestial.apply({
>                     constellations: {
>                         lineStyle: { stroke: `rgb(${color.rgb.r}, ${color.rgb.g}, ${color.rgb.b})`, width: 0.8, opacity: 0.8 }
>                     },
>                     stars: {
>                         style: {
>                             fill: `rgb(${color.rgb.r}, ${color.rgb.g}, ${color.rgb.b})`,
>                             opacity: `${color.rgb.a}`
>                         }
>                     },
>                 })

Styles, that I'm applying to the stars are displayed normally, but constellations become black and without any styles. Does anybody can help with this trouble?

**Comment by mauriciovillam** [comment]
I am having a similar issue when trying to turn it off/on with the apply method, it doesn't seem to show when I set constellation.lines to true

**Comment by mauriciovillam** [comment]
I'm experiencing the same issue, I have no idea what could be the cause.

**Comment by maisteRR** [comment]
> I'm experiencing the same issue, I have no idea what could be the cause.


If restarting the map is not a problem for you, then Celestial.display work fine

**Comment by mauriciovillam** [comment]
> > I'm experiencing the same issue, I have no idea what could be the cause.
> 
> If restarting the map is not a problem for you, then Celestial.display work fine

Hey! I already tried that. In my case I need to update the configuration many times and using Celestial.display seems to append data instead of overwriting it; which means after a lot of changes the browser runs out of memory and crashes.

**Comment by ofrohn** [comment]
Sorry for the late answer, I was very busy.
You managed to pick the two settings that were problematic.
The constellation line setting was my fault, Because the constellation styles can be different depending on rank (set in json data), the setting needs to be changed into an array. I did not do that for settings applied at runtime. 
You can of course directly specify an array of color values with up to three values if you want different colors.
The issue should be fixed now (v.0.7.30)
For the star fill color to work stars.style.colors = false also needs to be set, otherwise automatically generated spectral colors will be displayed.

**Comment by mauriciovillam** [comment]
Thank you very much, @ofrohn. 

@maisteRR could you confirm on your side that this is fixed?

**Comment by maisteRR** [comment]
thank you, @ofrohn

**Comment by rwardanjan** [comment]
I have still the same problem. I want to set default width of the lineStyle to 4 but it does not change...?
